<div class="container">
	<form class="form-signin" role="form" method="post" action="/user/password">
	   
        <div id="login-info" class="form-group form-signin-div-form">
            <label for="desc">首次登录修改密码</label>
        	<input id="passwd1" name="passwd1" type="password" class="form-control" placeholder="password" autocomplete="off">
        	<input id="passwd2" name="passwd2" type="password" class="form-control" placeholder="Password" autocomplete="off">
        </div>
        <div class="form-group form-signin-div-form">
        	<input type="submit" value="Submit" id="login-submit" class="btn btn-warning form-signin-div-button">
        </div>
      </form>
</div>
