<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<title>YOM--Yoho Own Manager</title>
<link rel="shortcut icon" href="/img/logo.ico" type="image/icon">

<!-- Bootstrap core CSS -->
<link href="/css/bootstrap.min.css" rel="stylesheet">
<link href="/css/om.css" rel="stylesheet">
<!-- Bootstrap core JS -->
<script src="/js/jquery-1.11.1.min.js"></script>
<script src="/js/bootstrap.min.js"></script>
</head>

<header>
	<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed"
					data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					<span class="sr-only">Toggle navigation</span> <span
						class="icon-bar"></span> <span class="icon-bar"></span> <span
						class="icon-bar"></span>
				</button>

				<div class="brand">
					<a class="navbar-brand" href="index.php"><span>三七美 OM</span></a>
					<!-- 			<a class="toogle pull-right"><i class="glyphicon glyphicon-chevron-left"></i></a> -->
					<ul class="nav navbar-nav navbar-right">
						<li id="nav_login"><a><?php echo $_SESSION['username']; ?></a></li>
						<li id="nav_signup"><a href="/login/logout">Logout</a></li>
					</ul>
				</div>

			</div>
		</div>
	</nav>
</header>

<div class="body slide">
	<aside class="sidebar show perfectScrollbar">
		<div id="solso-sidebar">
			<div class="panel-group" id="accordion" role="tablist"
				aria-multiselectable="true">
				<div class="panel panel-default">
					<div class="panel panel-default">
						<div class="panel-heading" role="tab" id="heading1">
							<h4 class="panel-title">
								<a href="index.php" class="single-item"> <i
									class="fa fa-dashboard"></i> Dashboard
								</a>
							</h4>
						</div>
					</div>
				</div>

				<div class="panel panel-default">
					<div class="panel-heading" role="tab" id="heading2">
						<h4 class="panel-title">
							<a data-toggle="collapse" data-parent="#accordion"
								href="#collapse2" aria-expanded="true" aria-controls="collapse2">
								<i class="fa fa-bar-chart-o"></i> Document <i
								class="pull-right fa fa-caret-down"></i>
							</a>
						</h4>
					</div>

					<div id="collapse2" class="panel-collapse collapse" role="tabpanel"
						aria-labelledby="heading2">
						<div>
							<a href="javascript:return false;" class="list-group-item">bar Chart</a> <a
								href="javascript:return false;" class="list-group-item">pie Chart</a> <a
								href="javascript:return false;" class="list-group-item">google Chart</a>
						</div>
					</div>
				</div>

				<div class="panel panel-default">
					<div class="panel-heading" role="tab" id="heading5">
						<h4 class="panel-title">
							<a data-toggle="collapse" data-parent="#accordion"
								href="#collapse5" aria-expanded="true" aria-controls="collapse5">
								<i class="fa fa-desktop"></i> 发布管理 <i
								class="pull-right fa fa-caret-down"></i>
							</a>
						</h4>
					</div>

					<div id="collapse5" class="panel-collapse collapse" role="tabpanel"
						aria-labelledby="heading5">
						<div>
							<a href="/release/releaseconfig" class="list-group-item">项目配置</a>
							<a href="/release/releasecode" class="list-group-item">代码发布</a>
						</div>
					</div>
				</div>


			</div>

		</div>
	</aside>
	<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-0 main">
		<?php echo $_content_;?>
	</div>
</div>
</body>
</html>