<div>
	<ul class="nav nav-tabs" role="tablist">
		<li role="presentation" class="active"><a href="#rel_conf_view"
			role="tab" data-toggle="tab">查看配置信息</a></li>
		<li role="presentation"><a href="#rel_conf_record" role="tab"
			data-toggle="tab">添加项目</a></li>
	    <li role="presentation"><a href="#rel_conf_monify" role="tab"
			data-toggle="tab">修改项目ip</a></li>
	</ul>

	<!-- Tab panes -->
	<div class="tab-content">

		<div role="tabpanel" class="tab-pane active" id="rel_conf_view">
			<table class="table table-striped" style="width: 100%;">
				<thead>
					<tr>
						<th class="om_table_th" style="width: 216px;">项目名称</th>
						<th class="om_table_th">位置</th>
						<th class="om_table_th">代码类型</th>
						<th class="om_table_th">项目代码仓库地址</th>
						<th class="om_table_th">生产环境服务器代码存放位置</th>
						<th class="om_table_th">生产环境服务器ip</th>
					</tr>
				</thead>
				<tbody>
					<?php 
					echo $html;
					?>
				</tbody>
			</table>
		</div>

		<div role="tabpanel" class="tab-pane" id="rel_conf_record">
			<form role="form" style="margin-top: 20px;" action="/release/releaseconfig?action=submit" method="post">
				<div class="form-group">
					<label for="desc">项目名称</label>
					<div class="form-group">
						<input type="text" name="rel_conf_project" class="om_input" placeholder=""> 
					</div>
				</div>
				<div class="form-group">
					<label for="desc">服务器位置</label>
					<div class="form-group">
						<select name="rel_conf_project_region" id="rel_conf_project_region" class="acc_record_form" style="width: 286px;">
					       <option value="aliyun">阿里云</option>
					       <option value="aws">亚马逊AWS</option>
					       <option value="tencent">腾讯云</option>
					       <option value="huidu">阿里云-灰度环境</option>
					       <option value="test">测试环境</option>
					   </select> 
					</div>
				</div>
				<div class="form-group">
					<label for="desc">项目开发语言</label>
					<div class="form-group">
					   <select name="rel_conf_project_language" id="rel_conf_project_language" class="om_input" onchange="getLanguage(this.value)">
					       <option value="php">php</option>
					       <option value="java">java</option>
					   </select>
				    </div>    
				</div>
				<div class="form-group" id="nginx_info">
					   
				</div>
				<div class="form-group" id="zookeeper">
					   
				</div>
				<div class="form-group">
					<label for="desc">项目代码仓库地址</label>
					<div class="form-group">
					   <select name="rel_conf_project_repository" id="rel_conf_project_repository" class="om_input" style="width: 76px;">
					       <option value="git">git</option>
					       <option value="svn">svn</option>
					   </select>
					   <input type="text" name="rel_conf_project_repository_url" class="om_input" placeholder="代码仓库地址"> 
					</div>
				</div>
				<div class="form-group">
					<label for="desc">生产环境服务器代码存放位置</label>
					<div class="form-group">
						<input type="text" name="rel_conf_project_code_path" class="om_input" placeholder="生产环境服务器代码绝对路径"> 
					</div>
				</div>
				<div class="form-group">
					<label for="desc">生产环境服务器ip</label>
					<div class="form-group">
						<textarea type="text" name="rel_conf_project_ip" style="margin: 0px; width: 286px; height: 214px;" class="rel_record_form_text" placeholder="每行填写一个ip。IDC和vpc内的机器，请写内网ip。阿里云请写公网ip。"></textarea>
					</div>
				</div>
				<div class="form-group">
					<button id="submit" type="submit" class="btn btn-success">Confirm</button>
				</div>
			</form>
		</div>
		
		
		<div role="tabpanel" class="tab-pane" id="rel_conf_monify">
		    <form role="form" style="margin-top: 20px;" action="/release/releaseconfig?action=update" method="post">
		        <div class="form-group" style="margin-top: 20px;">
				    <label for="desc">选择需要修改的应用</label>
				    <div class="form-group">
					   <select name="rel_app" id="rel_app" class="rel_record_form multiselect">
					   </select>
				    </div>
			    </div>
			    <div class="form-group">
				    <label for="desc">生产环境服务器ip</label>
				    <div class="form-group">
					   <textarea type="text" name="rel_conf_project_ip" style="margin: 0px; width: 286px; height: 214px;" class="rel_record_form_text" placeholder="每行填写一个ip。IDC和vpc内的机器，请写内网ip。阿里云请写公网ip。"></textarea>
				    </div>
			    </div>
			    <div class="form-group">
					<button id="submit" type="submit" class="btn btn-success">Confirm</button>
				</div>
			 </form>
		</div>

		<div class="modal fade bs-example-modal-lg" tabindex="-1"
			role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
			<div class="modal-dialog modal-lg">
				<div class="modal-content">
					<div class="modal-header">
						<h4 class="modal-title">Release Detail:</h4>
					</div>
					<div id="rel_detail" class="modal-body" style="word-wrap: break-word"></div>
					<div class="modal-header"></div>
					<div class="modal-header">
						<h4 class="modal-title">Release Checked Result:</h4>
					</div>
					<div id="rel_check_result" class="modal-body" style="word-wrap: break-word"></div>
					<div class="modal-footer">
						<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
					</div>
				</div>
			</div>
		</div>
		
	</div>
</div>

<script type="text/javascript" src="/js/release/release-detail.js" charset="UTF-8"></script>
<script type="text/javascript" src="/js/release/rel-java_nginx_info.js" charset="UTF-8"></script>
<script type="text/javascript" src="/js/release/select_rel_project.js" charset="UTF-8"></script>


