<div>
	<ul class="nav nav-tabs" role="tablist">
		<li role="presentation" class="active"><a href="#rel_release"
			role="tab" data-toggle="tab">Release</a></li>
	</ul>

	<!-- Tab panes -->
	<div class="tab-content">
		<div role="tabpanel" class="tab-pane active" id="rel_release">
			<div>
				
					<div class="form-group">
						<input type="hidden" name="rel_method" class="rel_record_form" value="git">
					</div>

					<div class="form-group">
						<label for="desc">选择需要发布的应用</label>
						<div class="form-group">
							<select name="rel_app" id="rel_app" class="om_input multiselect" onchange="getProjectinfo(this.value)">
							</select>
						</div>
					</div>
					<div id="rel_app_info">
					</div>

					<div class="form-group">
						<button id="next" type="submit" class="btn btn-success">
							&nbsp;&nbsp;Next&nbsp;&nbsp;</button>
						<button id="cancel" type="button" class="btn btn-default">Cancel</button>
					</div>
					<span id="spin"></span>
				
			</div>

		</div>

	</div>
</div>
<link href="/css/typeahead.css" rel="stylesheet"> 
<script src="/js/typeahead.bundle.js"></script>

<script src="/js/release/select_rel_project.js"></script>
<script src="/js/release/rel_info.js"></script>
<script src="/js/release/get_rel_action.js"></script>
<script src="/js/spin.min.js"></script>
<script src="/js/release/rel_action.js"></script>