	<div class="container-fluid left-border">
	<div class="row">
		<div class="col-md-12 col-lg-12">
			<h1><i class="fa fa-home"></i> Dashboard</h1>
			
<!-- 			<ol class="breadcrumb"> -->
<!-- 				<li><a href="index.php">Home</a></li> -->
<!-- 				<li><a href="#">Core</a></li> -->
<!-- 				<li><a href="#">Library</a></li> -->
<!-- 				<li class="active">Dashboard</li> -->
<!-- 			</ol>	 -->
		</div>
		COMING SOON!!
<!-- 		<div class="col-sm-6 col-md-3"> -->
<!-- 			<div class="widget widget-stats bg-green"> -->
<!-- 				<div class="stats-icon stats-icon-lg"><i class="fa fa-users fa-fw"></i></div> -->
<!-- 				<div class="stats-title">clients</div> -->
<!-- 				<div class="stats-number">38</div> -->
<!-- 				<hr> -->
<!-- 				<div class="stats-desc">total number of clients</div> -->
<!-- 			</div> 	 -->
<!-- 		</div> 	 -->

<!-- 		<div class="col-sm-6 col-md-3"> -->
<!-- 			<div class="widget widget-stats bg-blue"> -->
<!-- 				<div class="stats-icon stats-icon-lg"><i class="fa fa-puzzle-piece fa-fw"></i></div> -->
<!-- 				<div class="stats-title">products</div> -->
<!-- 				<div class="stats-number">24</div> -->
<!-- 				<hr> -->
<!-- 				<div class="stats-desc">total number of products</div> -->
<!-- 			</div> 	 -->
<!-- 		</div>   -->

<!-- 		<div class="col-sm-6 col-md-3"> -->
<!-- 			<div class="widget widget-stats bg-purple"> -->
<!-- 				<div class="stats-icon stats-icon-lg"><i class="fa fa-file-pdf-o fa-fw"></i></div> -->
<!-- 				<div class="stats-title">invoices</div> -->
<!-- 				<div class="stats-number">100</div> -->
<!-- 				<hr> -->
<!-- 				<div class="stats-desc">total number of invoices</div> -->
<!-- 			</div>  -->
<!-- 		</div> 		 -->

<!-- 		<div class="col-sm-6 col-md-3"> -->
<!-- 			<div class="widget widget-stats bg-grey"> -->
<!-- 				<div class="stats-icon stats-icon-lg"><i class="fa fa-money fa-fw"></i></div> -->
<!-- 				<div class="stats-title">AMOUNT</div> -->
<!-- 				<div class="stats-number">3432.89 $</div> -->
<!-- 				<hr> -->
<!-- 				<div class="stats-desc">total value of amounts</div> -->
<!-- 			</div>  -->
<!-- 		</div>  -->

<!-- 		<div class="col-md-12"> -->
<!-- 			<h2>Bootstrap Sidebar & Sidebar Accordion Menu</h2> -->
			
<!-- 			<p>Bootstrap is one of the most loved CSS framework used by web developers, but it has some shortcomings and one of this is an sidebar and an sidebar accordion menu.</p> -->
<!-- 			<p>I try to create a sidebar for Bootstrap only with bootstrap elements so any developer who want to use this app doesn't need to load other components to have access to this feature.</p> -->
<!-- 			<p>Bootstrap sidebar use localStorage, new modern concept to keep secure information in browser, to store active link.</p> -->
			
<!-- 			<h2>Sidebar Accordion Menu</h2> -->
			
<!-- 			<p>This is the main feature which make the goal of this application, sidebar menu are based on bootstrap accordion.</p> -->
<!-- 			<p>When web page is loaded, accordion menu leaves the sub-menu open if the sub-menu contains the current page link, making it very convenient for users to navigate through other items in the sub-menu, -->
<!-- 			 but with my modification this issue is solved.	 -->
<!-- 			</p> -->
			
<!-- 			<p>Bootstrap Sidebar & Sidebar Accordion Menu come with 2 themes blue and orange, of course anyone can customize this from .css file</p> -->
<!-- 		</div>		 -->
			
	</div>	
	</div>	