12332131
<div>
	<ul class="nav nav-tabs" role="tablist">
		<li role="presentation" class="active"><a href="#doc_om_view"
			role="tab" data-toggle="tab">查看信息</a></li>
		<li role="presentation"><a href="#doc_om_record" role="tab"
			data-toggle="tab">添加信息</a></li>
	    <li role="presentation"><a href="#doc_om_monify" role="tab"
			data-toggle="tab">修改信息</a></li>
	</ul>

	<!-- Tab panes -->
	<div class="tab-content">

		<div role="tabpanel" class="tab-pane active" id="rel_conf_view">
			<table class="table table-striped" style="width: 100%;">
				<thead>
					<tr>
						<th class="om_table_th" style="width: 216px;">项目名称</th>
						<th class="om_table_th">位置</th>
						<th class="om_table_th">代码类型</th>
						<th class="om_table_th">项目代码仓库地址</th>
						<th class="om_table_th">生产环境服务器代码存放位置</th>
						<th class="om_table_th">生产环境服务器ip</th>
					</tr>
				</thead>
				<tbody>
					<?php 
					echo $html;
					?>
				</tbody>
			</table>
		</div>

		<div role="tabpanel" class="tab-pane" id="doc_om__record">
			<form role="form" style="margin-top: 20px;" action="/release/releaseconfig?action=submit" method="post">
				<div class="form-group">
					<label for="desc">项目名称</label>
					<div class="form-group">
						<input type="text" name="rel_conf_project" class="om_input" placeholder=""> 
					</div>
				</div>
				<div class="form-group">
					<label for="desc">服务器位置</label>
					<div class="form-group">
						<select name="rel_conf_project_region" id="rel_conf_project_region" class="om_input" style="width: 286px;">
					       <option value="aliyun">阿里云</option>
					       <option value="aws">亚马逊AWS</option>
					       <option value="tencent">腾讯云</option>
					       <option value="huidu">阿里云-灰度环境</option>
					       <option value="test">测试环境</option>
					   </select> 
					</div>
				</div>
				<div class="form-group">
					<label for="desc">项目开发语言</label>
					<div class="form-group">
					   <select name="rel_conf_project_language" id="rel_conf_project_language" class="om_input" onchange="getLanguage(this.value)">
					       <option value="php">php</option>
					       <option value="java">java</option>
					   </select>
				    </div>    
				</div>
				<div class="form-group" id="nginx_info">
					   
				</div>
				<div class="form-group" id="zookeeper">
					   
				</div>
				<div class="form-group">
					<label for="desc">项目代码仓库地址</label>
					<div class="form-group">
					   <select name="rel_conf_project_repository" id="rel_conf_project_repository" class="om_input" style="width: 76px;">
					       <option value="git">git</option>
					       <option value="svn">svn</option>
					   </select>
					   <input type="text" name="rel_conf_project_repository_url" class="om_input" placeholder="代码仓库地址"> 
					</div>
				</div>
				<div class="form-group">
					<label for="desc">生产环境服务器代码存放位置</label>
					<div class="form-group">
						<input type="text" name="rel_conf_project_code_path" class="om_input" placeholder="生产环境服务器代码绝对路径"> 
					</div>
				</div>
				<div class="form-group">
					<label for="desc">生产环境服务器ip</label>
					<div class="form-group">
						<textarea type="text" name="rel_conf_project_ip" style="margin: 0px; width: 286px; height: 214px;" class="om_input" placeholder="每行填写一个ip。IDC和vpc内的机器，请写内网ip。阿里云请写公网ip。"></textarea>
					</div>
				</div>
				<div class="form-group">
					<button id="submit" type="submit" class="btn btn-success">Confirm</button>
				</div>
			</form>
		</div>
		
		
		<div role="tabpanel" class="tab-pane" id="doc_om__monify">
		    <form role="form" style="margin-top: 20px;" action="/release/releaseconfig?action=update" method="post">
		        <div class="form-group" style="margin-top: 20px;">
				    <label for="desc">选择需要修改的应用</label>
				    <div class="form-group">
					   <select name="rel_app" id="rel_app" class="om_input multiselect">
					   </select>
				    </div>
			    </div>
			    <div class="form-group">
				    <label for="desc">生产环境服务器ip</label>
				    <div class="form-group">
					   <textarea type="text" name="rel_conf_project_ip" style="margin: 0px; width: 286px; height: 214px;" class="om_input" placeholder="每行填写一个ip。请写内网ip。"></textarea>
				    </div>
			    </div>
			    <div class="form-group">
					<button id="submit" type="submit" class="btn btn-success">Confirm</button>
				</div>
			 </form>
		</div>
		
	</div>
</div>



