<div>
	<ul class="nav nav-tabs" role="tablist">
		<li role="presentation" class="active"><a href="#doc_om_view"
			role="tab" data-toggle="tab">查看信息</a></li>
		<li role="presentation"><a href="#doc_om_record" role="tab"
			data-toggle="tab">添加信息</a></li>
	    <li role="presentation"><a href="#doc_om_monify" role="tab"
			data-toggle="tab">修改信息</a></li>
	</ul>

	<!-- Tab panes -->
	<div class="tab-content">

		<div role="tabpanel" class="tab-pane active" id="doc_om_view">
			<table class="table table-striped" style="width: 100%;">
				<thead>
					<tr>
						<th class="om_table_th" style="width: 216px;">项目名称</th>
						<th class="om_table_th">位置</th>
						<th class="om_table_th">代码类型</th>
						<th class="om_table_th">项目代码仓库地址</th>
						<th class="om_table_th">生产环境服务器代码存放位置</th>
						<th class="om_table_th">生产环境服务器ip</th>
					</tr>
				</thead>
				<tbody>
					<?php 
					echo $html;
					?>
				</tbody>
			</table>
		</div>

		<div role="tabpanel" class="tab-pane" id="doc_om_record">
			<form role="form" style="margin-top: 20px;" action="/doc/record" method="post">
				<div class="form-group">
					<label for="desc">描述</label>
					<div class="form-group">
						<input type="text" name="doc_decs" class="om_input" placeholder=""> 
					</div>
				</div>
				
				<div class="form-group">
					<label for="desc">用户名</label>
					<div class="form-group">
					   <input type="text" name="doc_user" class="om_input" placeholder="">
				    </div>    
				</div>

				<div class="form-group">
					<label for="desc">密码</label>
					<div class="form-group">
						<input type="text" name="doc_password" class="om_input" placeholder=""> 
					</div>
				</div>
				
				<div class="form-group">
					<label for="desc">类别</label>
					<div class="form-group">
						<select name="doc_group" id="doc_group" class="om_input" style="width: 286px;">
					       <option value="platform">平台</option>
					       <option value="system">系统</option>
					       <option value="app">应用</option>
					   </select> 
					</div>
				</div>
				
				<div class="form-group">
					<label for="desc">备注</label>
					<div class="form-group">
						<input type="text" name="doc_common" class="om_input" placeholder=""> 
					</div>
				</div>
				
				<div class="form-group">
					<button id="submit" type="submit" class="btn btn-success">Confirm</button>
				</div>
			</form>
		</div>
		
		
		<div role="tabpanel" class="tab-pane" id="doc_om_monify">
		    <form role="form" style="margin-top: 20px;" action="/doc/record?action=update" method="post">
		        <div class="form-group" style="margin-top: 20px;">
				    <label for="desc">选择需要修改的信息</label>
				    <div class="form-group">
					   <input type="text" name="doc_monify_desc" id="doc_monify_desc" class="typeahead om_input" placeholder="" data-provide="typeahead">
				    </div>
			    </div>
			    
			    <div class="form-group">
					<label for="desc">用户名</label>
					<div class="form-group">
					   <input type="text" name="doc_monify_user" class="om_input" placeholder="">
				    </div>    
				</div>

				<div class="form-group">
					<label for="desc">密码</label>
					<div class="form-group">
						<input type="text" name="doc_monify_password" class="om_input" placeholder=""> 
					</div>
				</div>
				
				<div class="form-group">
					<label for="desc">备注</label>
					<div class="form-group">
						<input type="text" name="doc_monify_common" class="om_input" placeholder=""> 
					</div>
				</div>
			    
			    <div class="form-group">
					<button id="submit" type="submit" class="btn btn-success">Confirm</button>
				</div>
			 </form>
		</div>
		
	</div>
</div>
<link href="/css/typeahead.css" rel="stylesheet"> 
<script src="/js/typeahead.bundle.js"></script>

<script type="text/javascript" src="/js/doc/get_doc_desc.js" charset="UTF-8"></script>


